name : Junit CI

## PUSHされた時にCIを実行する
on:
  [push]

## 実際に実行するジョブを設定する
## 今回はビルドとテストを実行する
jobs:
  build:
    ## 実行環境を設定する。今回はGithubが自前で用意しているホステッドランナーを利用
    runs-on: ubuntu-latest
  
  steps:
      ## Runnerにgitリポジトリのコピーをダウンロード
      - uses: actions/checkout@v4

      # Java 17をセットアップ
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache : maven

      ## maven build jarファイルを作成するためのコマンド
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      ## Test実行 Junitテストを実行するためのコマンド
      - name : Test with Maven
        run : mvn --batch-mode test

